### ISSUE TITLE
The app  crashed when i wanted to add  a new entry

### ISSUE THREAD

**Issue by adewararilwan** [SecUSo/privacy-friendly-food-tracker#55]
MY SHORT EXPERIENCE ON FOOD TRACKER
Not long ago, I was thinking of the best way to start tracking my daily calorie consumption. I searched using Google and after a long search found the food tracker Android application. I went on to read the write-up concerning the application and found it very interesting and simple. I was impressed with the functionality, downloaded the application from Fossdroid.com
After downloading, I installed the food tracker application and immediately opened it after installation. It pops up with a welcome note. I was at first relieved that I have found the right application to help achieve the goal of tracking my daily calorie consumption but to my disbelief, the experience was shocking because it came up with unexpected behavior.

REPORTING THE BUG
Expected Behaviour
The application should have open an overview screen for the consumed calories of the chosen date where I can add an entry when I touch the "+" symbol immediately without taking any time.

Actual Behaviour
When I touch a day on the calendar to input a new entry as a first time user, it crashed saying (Food tracker has stooped).

HOW TO REPRODUCE
1.Download the Food tracker application
2. Open the application
It shows a welcome message, Key elements, Github and guide and lastly shows Calendar
3.  Touch a day to insert a new entry
4. Noticing the Bug

App version: 1.0.1
Smartphone: Tecno WX3
Operating System - Android 7.0

RECORDING THE BUG
https://www.youtube.com/watch?v=TWFqEcVjjjQ

GITHUB PROFILE:
https://github.com/adewararilwan

**Comment by crimsonskylark** [comment]
I was able to replicate this and I think I traced the bug to https://github.com/SecUSo/privacy-friendly-food-tracker/blob/53b7fd752669a29ea65dee4a9dfc80cfc78d9828/app/src/main/java/org/secuso/privacyfriendlyfoodtracker/activities/adapter/DatabaseFacade.java#L44 which seems to be accessing a `null` instance returned by `getInstance()`, which in turn leads https://github.com/SecUSo/privacy-friendly-food-tracker/blob/53b7fd752669a29ea65dee4a9dfc80cfc78d9828/app/src/main/java/org/secuso/privacyfriendlyfoodtracker/activities/OverviewActivity.java#L254 to return `null` as well causing https://github.com/SecUSo/privacy-friendly-food-tracker/blob/53b7fd752669a29ea65dee4a9dfc80cfc78d9828/app/src/main/java/org/secuso/privacyfriendlyfoodtracker/activities/OverviewActivity.java#L275 to be `null` and raising `NullPointerException` when accessed at https://github.com/SecUSo/privacy-friendly-food-tracker/blob/53b7fd752669a29ea65dee4a9dfc80cfc78d9828/app/src/main/java/org/secuso/privacyfriendlyfoodtracker/activities/OverviewActivity.java#L276

Unfortunately since I am unfamiliar with both Java and Android I can neither confirm that this is the bug's origin nor submit a fix. Hopefully the information is at least partially correct and helps with the fix.

**Comment by Kamuno** [comment]
Fixed via fd1c35e85416d8fefdbffb0f93cb5345186c3b34
